name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # "adopt" is deprecated, use "temurin"

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2  # This installs Gradle automatically

      - name: Build and test
        working-directory: .
        run: |
          export SHELL=/bin/bash
          gradle build  # Using installed Gradle instead of ./gradlew
